# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 14:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    replaces = [('comparisons', '0001_initial'), ('comparisons', '0002_auto_20160106_0205'), ('comparisons', '0003_comparisonitem'), ('comparisons', '0004_comparisonitem_comparison'), ('comparisons', '0005_comparison_date_starting'), ('comparisons', '0006_auto_20160107_0230'), ('comparisons', '0007_auto_20160107_0237'), ('comparisons', '0008_comparisonitem_score'), ('comparisons', '0009_auto_20160108_0323'), ('comparisons', '0010_auto_20160108_0325'), ('comparisons', '0011_auto_20160114_0040'), ('comparisons', '0012_auto_20160114_0445'), ('comparisons', '0013_auto_20160115_0847')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='What should it be called?')),
                ('description', models.TextField(blank=True, verbose_name='Outline the rules, guidelines, and anything else important about this comparison.')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_ending', models.DateField(blank=True, null=True, verbose_name='When should we finish?')),
                ('active', models.BooleanField(default=True, verbose_name='Is it happening right now?')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('date_starting', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='When should we start?')),
            ],
        ),
        migrations.CreateModel(
            name='ComparisonItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Give a brief description of the submission')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comparison', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='comparisons.Comparison')),
                ('score', models.IntegerField(default=1400)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to=b'20160115134742679')),
            ],
        ),
    ]
