# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 20:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comparisons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Give a brief description of the submission')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField(default=1400)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to=b'20160116204343893')),
            ],
        ),
        migrations.AddField(
            model_name='comparison',
            name='date_starting',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='When should we start?'),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Is it happening right now?'),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='date_ending',
            field=models.DateField(blank=True, null=True, verbose_name='When should we finish?'),
        ),
        migrations.AddField(
            model_name='comparisonitem',
            name='comparison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparisons.Comparison'),
        ),
        migrations.AddField(
            model_name='comparisonitem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
