# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparison',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Is it happening right now?'),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='date_ending',
            field=models.DateTimeField(blank=True, verbose_name='When should we finish?'),
        ),
    ]
