# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 21:03
from __future__ import unicode_literals

import compare.comparisons.models
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0002_auto_20160116_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonitem',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to=compare.comparisons.models.upload_to),
        ),
    ]
