# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 19:57
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0002_auto_20160115_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonitem',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to=b'20160116195719357'),
        ),
    ]
