# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0003_comparisonitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonitem',
            name='comparison',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='comparisons.Comparison'),
            preserve_default=False,
        ),
    ]
