# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0003_auto_20160116_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonItemVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_initial_score', models.IntegerField(default=1400)),
                ('loser_initial_score', models.IntegerField(default=1400)),
                ('score_change', models.IntegerField(default=0)),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loser', to='comparisons.ComparisonItem')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='comparisons.ComparisonItem')),
            ],
        ),
    ]
