# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 07:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0004_comparisonitem_comparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='date_starting',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 1, 7, 7, 29, 56, 598923, tzinfo=utc), verbose_name='When should we start?'),
        ),
    ]
