# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0006_auto_20160107_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparison',
            name='date_ending',
            field=models.DateTimeField(blank=True, null=True, verbose_name='When should we finish?'),
        ),
    ]
