# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0008_comparisonitem_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparisonitem',
            name='image_url',
        ),
        migrations.AddField(
            model_name='comparisonitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='CIs'),
        ),
    ]
