# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0009_auto_20160108_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonitem',
            name='image',
            field=models.ImageField(upload_to='CIs'),
        ),
    ]
