# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 05:40
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0010_auto_20160108_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonitem',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to=b'20160114054005911'),
        ),
    ]
