# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0011_auto_20160114_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparison',
            name='date_ending',
            field=models.DateField(blank=True, null=True, verbose_name='When should we finish?'),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='date_starting',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='When should we start?'),
        ),
        migrations.AlterField(
            model_name='comparisonitem',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to=b'20160114094528515'),
        ),
    ]
