# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 13:47
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0012_auto_20160114_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonitem',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to=b'20160115134742679'),
        ),
    ]
